// user
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
// widget actions after login
export const FETCH_WIDGET_BEGIN = "FETCH_WIDGET_BEGIN";
export const FETCH_WIDGET_SUCCESS = "FETCH_WIDGET_SUCCESS";
export const FETCH_WIDGET_FAIL = "FETCH_WIDGET_FAIL";
// messages
export const FETCH_MESSAGES_BEGIN = "FETCH_MESSAGES_BEGIN";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";

// app
export const OPEN_MOBILE_PAGE_NAV = "OPEN_MOBILE_PAGE_NAV";
export const OPEN_USER_ACTIONS = "OPEN_USER_ACTIONS";
export const OPEN_YOUR_POSTS = "OPEN_YOUR_POSTS";
export const OPEN_YOUR_GROUPS = "OPEN_YOUR_GROUPS";
export const OPEN_CURRENT_USER = "OPEN_CURRENT_USER";

// posts
// export const FETCH_POSTS_BEGIN = "FETCH_POSTS_BEGIN";
// export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
// export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
// groups
// export const FETCH_GROUPS_BEGIN = "FETCH_GROUPS_BEGIN";
// export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
// export const FETCH_GROUPS_FAIL = "FETCH_GROUPS_FAIL";

// messages

export const SEND_RECEIVE_MESSAGE = "SEND_RECEIVE_MESSAGE";
export const READ_MESSAGE = "READ_MESSAGE";
export const REPLY_TO_MESSAGE = "REPLY_TO_MESSAGE";
