// app
export const OPEN_MOBILE_PAGE_NAV = "OPEN_MOBILE_PAGE_NAV";
export const OPEN_USER_ACTIONS = "OPEN_USER_ACTIONS";
export const OPEN_YOUR_POSTS = "OPEN_YOUR_POSTS";
export const OPEN_YOUR_GROUPS = "OPEN_YOUR_GROUPS";
export const OPEN_CURRENT_USER = "OPEN_CURRENT_USER";
export const TOGGLE_THEME = "TOGGLE_THEME";
// user
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
// widget actions after login
export const FETCH_WIDGET_BEGIN = "FETCH_WIDGET_BEGIN";
export const FETCH_WIDGET_SUCCESS = "FETCH_WIDGET_SUCCESS";
export const FETCH_WIDGET_FAIL = "FETCH_WIDGET_FAIL";
